server:
  port: 8800

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: toor

  kafka:
    bootstrap-servers:
      - localhost:8084
      - localhost:8083
    consumer:
      auto-offset-reset: earliest
      group-id: db_group
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer